# Generated by Django 4.0.4 on 2022-06-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Pages', 'verbose_name_plural': 'Pages'},
        ),
    ]
